### ISSUE TITLE
[Question] Trying to expose specific methods only

### ISSUE THREAD

**Issue by Konijima** [binier/tiny-typed-emitter#10]
Hi, I am trying to expose only the following methods to an API:
- `on`, `once`, `off`

I want to emit stuff internally and expose only those 3 methods.

Here what I got as of now:
```ts
interface SocketEvents {
    'socket-connected': () => void
    'socket-disconnected': () => void
    'socket-reply': (event: string, ...params: any[]) => void
    'socket-error': (event: string, error: any) => void
}
class SocketEventEmitter extends TypedEmitter<SocketEvents> {
    constructor() { super() }
}
const eventEmitter = new SocketEventEmitter()

export function on(event: keyof SocketEvents, listener: SocketEvents[keyof SocketEvents]) {
    eventEmitter.on(event, listener)
}
export function once(event: keyof SocketEvents, listener: SocketEvents[keyof SocketEvents]) {
    eventEmitter.once(event, listener)
}
export function off(event: keyof SocketEvents, listener: SocketEvents[keyof SocketEvents]) {
    eventEmitter.off(event, listener)
}
```
The problem I'm facing with this, is the exported on, once, off doesn't automatically detect the correct listener to use.
I believe it might just be something to do with `listener: SocketEvents[keyof SocketEvents]`.

I was wondering if anyone would have a solution for this.

**Edit:**
I tried this also
```ts
export const on = eventEmitter.on
export const once = eventEmitter.once
export const off = eventEmitter.off
```
But the return of the call expose the whole object

**Comment by binier** [comment]
Hi, this is more Typescript question, than question for this package and I haven't written any Typescript/Javascript for more than a year, but I'll try to help anyways.

Since you are `extends TypedEmitter<SocketEvents>` extending `TypedEmitter`, you are inheriting all of it's functions. It should work if you wrap `TypedEmitter` instead of extending it and then delagate `on`, `once` and `off` methods to inner typed emitter.
```ts
class SocketEventEmitter {
    private inner: TypedEmitter<SocketEvents>;
}
```

**Comment by Konijima** [comment]
> Hi, this is more Typescript question, than question for this package and I haven't written any Typescript/Javascript for more than a year, but I'll try to help anyways.
> 
> Since you are `extends TypedEmitter<SocketEvents>` extending `TypedEmitter`, you are inheriting all of it's functions. It should work if you wrap `TypedEmitter` instead of extending it and then delagate `on`, `once` and `off` methods to inner typed emitter.
> 
> ```ts
> class SocketEventEmitter {
>     private inner: TypedEmitter<SocketEvents>;
> }
> ```

That's right, I will try that.
Thanks alot.
