### ISSUE TITLE
Can we use the emit method with a variable for the event name instead of string?

### ISSUE THREAD

**Issue by hga77** [binier/tiny-typed-emitter#2]
When emitting, can we use a variable instead of a string?

like this:
`this.emit(some_variable, args)`

**Comment by binier** [comment]
As long as you store string in `some_variable` of course.

You can use non string variable by casting it to `any`, but with that you will lose type checking.

**Comment by hga77** [comment]
Thanks. I tried but I get an error with type any. I have kept it as a string following the example provided.

**Comment by binier** [comment]
Please provide me with a minimal example which reproduces a bug.
