### ISSUE TITLE
adding typed events to an extended class that extends EventEmitter?

### ISSUE THREAD

**Issue by fent** [binier/tiny-typed-emitter#5]
hi, i'm creating a class that extends the Stream class, which extends EventEmitter. does this module support adding typed events to such classes?

```js
interface MyEvents {
  'foo': () => void;
}

// how do I fit `TypedEmitter` here so that `MyClass` has the `foo` event and also extends `Stream`?
class MyClass extends Stream {
  constructor() {
  }
}
```

**Comment by binier** [comment]
It's more of a Typescript related question.

You'll need to make `Stream` generic as well where it accepts `MyEvents` as type parameter:
```typescript
import { TypedEmitter, ListenerSignature, DefaultListener } from 'tiny-typed-emitter';

class Stream<L extends ListenerSignature<L> = DefaultListener> extends TypedEmitter<L> {
}
```
Then use it with `MyClass`:
```typescript
class MyClass extends Stream<MyEvents> {
}
```

**Comment by fent** [comment]
`Stream` comes from node's `stream` module. I'm not able to change its definition :/

**Comment by binier** [comment]
You have 2 options:

1. Add getter `emitter` or something like that to cast to `TypedEmitter`:
```typescript
class MyClass extends Stream {
  get emitter() {
    return this as TypedEmitter<MyEvents>;
  }
}
```
2. Override `EventEmitter` methods on `MyClass`:
```typescript
interface MyEvents {
  'foo': () => void;
}

class MyClass extends Stream {
  on<E extends keyof MyEvents>(event: E, listener: MyEvents[E]): this {
    return this.on(event, listener);
  }
}
```
Use this as a [reference](https://github.com/binier/tiny-typed-emitter/blob/master/lib/index.d.ts) to override other methods as needed(basically substitute `L` with `MyEvents` everywhere and you are good to go).
